package Erecruit_Login;

/**
 *
 * @author Chatzopoulos Thomas
 */

import javax.swing.*;
import java.sql.*;
import java.awt.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;

public class AdminGui extends javax.swing.JFrame {
    String username;
    Connection conn=null;
    Statement stmt=null;
    PreparedStatement pst=null;
    ResultSet rs=null;
    
    public AdminGui(String username) {
        this.username = username;
        try
        {
            conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/erecruit" , "root" , "123qweasdzxc,");     
        }
        catch(Exception Ex)
        {
            JOptionPane.showMessageDialog(null,Ex);
        }
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        newCandidateJButton = new javax.swing.JButton();
        viewYourDatajButton = new javax.swing.JButton();
        viewYourDatajScrollPane1 = new javax.swing.JScrollPane();
        UserTable = new javax.swing.JTable();
        updateUserJButton = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        newRecruiterJButton = new javax.swing.JButton();
        newTomeasJButton = new javax.swing.JButton();
        newAntikeimJButton = new javax.swing.JButton();
        showHistoryJButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        historyTable = new javax.swing.JTable();
        historyToblesComboBox = new javax.swing.JComboBox<String>();
        jLabel1 = new javax.swing.JLabel();
        userscombobox = new javax.swing.JComboBox();
        jButton2 = new javax.swing.JButton();
        startDateTextField = new javax.swing.JTextField();
        startdatelabel = new javax.swing.JLabel();
        enddatelabel = new javax.swing.JLabel();
        endDateTextField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1320, 800));

        newCandidateJButton.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        newCandidateJButton.setForeground(new java.awt.Color(34, 200, 75));
        newCandidateJButton.setText("New Candidate");
        newCandidateJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newCandidateJButtonActionPerformed(evt);
            }
        });

        viewYourDatajButton.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        viewYourDatajButton.setForeground(new java.awt.Color(30, 120, 255));
        viewYourDatajButton.setText("View your data");
        viewYourDatajButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewYourDatajButtonActionPerformed(evt);
            }
        });

        UserTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "username", "password", "name", "surname", "reg_date", "email", "lastLogIn"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, true, true, true, true, true, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        viewYourDatajScrollPane1.setViewportView(UserTable);

        updateUserJButton.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        updateUserJButton.setForeground(new java.awt.Color(230, 135, 45));
        updateUserJButton.setText("Update User");
        updateUserJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateUserJButtonActionPerformed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 0, 0));
        jButton1.setText("Exit");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        newRecruiterJButton.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        newRecruiterJButton.setForeground(new java.awt.Color(34, 200, 75));
        newRecruiterJButton.setText("New Recruiter");
        newRecruiterJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newRecruiterJButtonActionPerformed(evt);
            }
        });

        newTomeasJButton.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        newTomeasJButton.setForeground(new java.awt.Color(34, 200, 75));
        newTomeasJButton.setText("New Tomeas");
        newTomeasJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newTomeasJButtonActionPerformed(evt);
            }
        });

        newAntikeimJButton.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        newAntikeimJButton.setForeground(new java.awt.Color(34, 200, 75));
        newAntikeimJButton.setText("New Antikeim");
        newAntikeimJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newAntikeimJButtonActionPerformed(evt);
            }
        });

        showHistoryJButton.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        showHistoryJButton.setForeground(new java.awt.Color(230, 135, 45));
        showHistoryJButton.setText("Show History of chosen Table");
        showHistoryJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showHistoryJButtonActionPerformed(evt);
            }
        });

        historyTable.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        historyTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ID", "User", "Table", "Title succes", "Kind of change", "Date"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(historyTable);

        historyToblesComboBox.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        historyToblesComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "candidate", "recruiter", "user", "etaireia", "job" }));
        historyToblesComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                historyToblesComboBoxActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(30, 120, 255));
        jLabel1.setText("Hello Admin!");

        userscombobox.setEditable(true);
        userscombobox.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        userscombobox.setMaximumRowCount(40);

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton2.setForeground(new java.awt.Color(230, 135, 45));
        jButton2.setText("Show History of chosen user");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        startdatelabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        startdatelabel.setText("Start Date :");

        enddatelabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        enddatelabel.setText("End Date :");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Please enter the dates in which you want to check the history");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Then choose one of the users whose history you want to check");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Please enter the table of which you want to check the history");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Note: the dates shoud be of this form:");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("YYYY-MM-DD HH:MM:SS");

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton3.setForeground(new java.awt.Color(30, 120, 255));
        jButton3.setText("Show Users");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(showHistoryJButton)
                .addGap(254, 254, 254))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addComponent(startdatelabel)
                                .addGap(18, 18, 18)
                                .addComponent(startDateTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(enddatelabel)
                                .addGap(18, 18, 18)
                                .addComponent(endDateTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(20, 20, 20)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(51, 51, 51)
                                        .addComponent(jLabel6))
                                    .addComponent(jLabel5)))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(viewYourDatajScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 986, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(6, 6, 6)
                                    .addComponent(updateUserJButton))
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(86, 86, 86)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jLabel1)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jButton1))
                                        .addComponent(viewYourDatajButton))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(51, 51, 51)
                                .addComponent(historyToblesComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel3)
                                    .addGap(30, 30, 30)
                                    .addComponent(jButton3)
                                    .addGap(18, 18, 18)
                                    .addComponent(userscombobox, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(32, 32, 32)
                                    .addComponent(jButton2))
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1082, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(385, 385, 385)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(newCandidateJButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(newRecruiterJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(51, 51, 51)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(newAntikeimJButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(newTomeasJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addGap(45, 45, 45))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)))
                .addComponent(viewYourDatajButton)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(viewYourDatajScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(updateUserJButton)))
                .addGap(59, 59, 59)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(newCandidateJButton)
                        .addGap(31, 31, 31)
                        .addComponent(newRecruiterJButton))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(newAntikeimJButton)
                        .addGap(31, 31, 31)
                        .addComponent(newTomeasJButton)))
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(historyToblesComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(showHistoryJButton))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(startdatelabel)
                            .addComponent(startDateTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(enddatelabel)
                            .addComponent(endDateTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addComponent(jLabel6)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jButton2))
                        .addGap(26, 26, 26)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButton3)
                        .addComponent(userscombobox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(81, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void newRecruiterJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newRecruiterJButtonActionPerformed
        newRecruiter nRec = new newRecruiter();
        nRec.setVisible(true);
    }//GEN-LAST:event_newRecruiterJButtonActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void updateUserJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateUserJButtonActionPerformed
        try
        {
            String updated;
            String UserUpdateQuery = "update user";

            for(int i=0;i<UserTable.getColumnCount();i++)
            {
                updated = UserTable.getValueAt(0, i).toString();
                if(i==0)
                UserUpdateQuery += " set " +UserTable.getColumnName(i) +" = '" +updated +"'";
                else
                UserUpdateQuery += " , " +UserTable.getColumnName(i) +" = '" +updated +"'";
            }
            UserUpdateQuery += " where username LIKE '%" +this.username +"%'";

            JOptionPane.showMessageDialog(null, UserUpdateQuery);

            Statement stmt = conn.createStatement();
            pst =conn.prepareStatement(UserUpdateQuery);
            pst.executeUpdate();
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_updateUserJButtonActionPerformed

    private void historyToblesComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_historyToblesComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_historyToblesComboBoxActionPerformed

    private void viewYourDatajButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewYourDatajButtonActionPerformed
        try
        {
            if(UserTable.getRowCount()>0)
            ((DefaultTableModel)UserTable.getModel()).removeRow(0);

            String userQuery =
            "select * from user"
            + " where username LIKE '%" +this.username +"%';" ;

            DefaultTableModel temporaryTable = (DefaultTableModel) UserTable.getModel();
            Statement stmt = conn.createStatement();
            ResultSet rs = stmt.executeQuery(userQuery);
            while(rs.next())
            {
                temporaryTable.addRow(new Object[] { rs.getString("username"), rs.getString("password") , rs.getString("name"),
                    rs.getString("surname") , rs.getString("reg_date"), rs.getString("email"), rs.getString("lastLogIn")});
        }
        UserTable.setModel(temporaryTable);
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null,e);
        }
    }//GEN-LAST:event_viewYourDatajButtonActionPerformed

    private void newCandidateJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newCandidateJButtonActionPerformed
        newCandidate nCandi = new newCandidate();
        nCandi.setVisible(true);
    }//GEN-LAST:event_newCandidateJButtonActionPerformed

    private void showHistoryJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showHistoryJButtonActionPerformed
        try
        {
            int height = historyTable.getRowCount();
            for(int i=0;i<height;i++)
            {
                ((DefaultTableModel)historyTable.getModel()).removeRow(0);
            }
            
            String table = historyToblesComboBox.getSelectedItem().toString();
            String userQuery = "select * from history where table_name LIKE '%" + table +"%';" ;

            DefaultTableModel temporaryTable = (DefaultTableModel) historyTable.getModel();
            Statement stmt = conn.createStatement();
            ResultSet rs = stmt.executeQuery(userQuery);
            while(rs.next())
            {
                temporaryTable.addRow(new Object[] { rs.getString("historyID"), rs.getString("user_username") , rs.getString("table_name"),
                    rs.getString("success") , rs.getString("eidos"), rs.getString("event_date")});
            }
            historyTable.setModel(temporaryTable);
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null,e);
        }
    }//GEN-LAST:event_showHistoryJButtonActionPerformed

    private void newAntikeimJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newAntikeimJButtonActionPerformed
        newAntikeim nAnti = new newAntikeim();
        nAnti.setVisible(true);
    }//GEN-LAST:event_newAntikeimJButtonActionPerformed

    private void newTomeasJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newTomeasJButtonActionPerformed
        newTomeas nTom = new newTomeas();
        nTom.setVisible(true);
    }//GEN-LAST:event_newTomeasJButtonActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        try
        {
            userscombobox.removeAllItems();
            
            String users = "select username from user";
            Statement stmt1 = conn.createStatement();
            ResultSet rs1 = stmt1.executeQuery(users);
            
            while(rs1.next())
            {
                String name = rs1.getString("username");
                userscombobox.addItem(name);
            }
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        String startdate = startDateTextField.getText();
        String enddate = endDateTextField.getText(); 
        String usern = userscombobox.getSelectedItem().toString();
        
        try
        {
            int height = historyTable.getRowCount();
            for(int i=0;i<height;i++)
            {
                ((DefaultTableModel)historyTable.getModel()).removeRow(0);
            }
            
            String query = "select * from history where user_username LIKE '%" +usern +"%' AND event_date > '" +startdate +"' AND event_date < '" +enddate +"'";
            
            DefaultTableModel temporaryTable = (DefaultTableModel) historyTable.getModel();
            Statement stmt = conn.createStatement();
            ResultSet rs = stmt.executeQuery(query);
            
            while(rs.next())
            {
                temporaryTable.addRow(new Object[] { rs.getString("historyID"), rs.getString("user_username") , rs.getString("table_name"),
                    rs.getString("success") , rs.getString("eidos"), rs.getString("event_date")});
            }
            
            historyTable.setModel(temporaryTable);
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_jButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable UserTable;
    private javax.swing.JTextField endDateTextField;
    private javax.swing.JLabel enddatelabel;
    private javax.swing.JTable historyTable;
    private javax.swing.JComboBox<String> historyToblesComboBox;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton newAntikeimJButton;
    private javax.swing.JButton newCandidateJButton;
    private javax.swing.JButton newRecruiterJButton;
    private javax.swing.JButton newTomeasJButton;
    private javax.swing.JButton showHistoryJButton;
    private javax.swing.JTextField startDateTextField;
    private javax.swing.JLabel startdatelabel;
    private javax.swing.JButton updateUserJButton;
    private javax.swing.JComboBox userscombobox;
    private javax.swing.JButton viewYourDatajButton;
    private javax.swing.JScrollPane viewYourDatajScrollPane1;
    // End of variables declaration//GEN-END:variables
}
