/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Erecruit_Login;

/**
 *
 * @author Chatzopoulos Thomas
 */

import javax.swing.*;
import java.sql.*;
import java.awt.*;
import static java.time.Instant.now;
import java.time.LocalDate;
import java.time.ZoneId;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;
import java.util.Date;
import java.text.SimpleDateFormat;

public class newAntikeim extends javax.swing.JFrame {
    String username;
    Connection conn=null;
    Statement stmt=null;
    PreparedStatement pst=null;
    ResultSet rs=null;
    String newUsername;    
    /**
     * Creates new form newAntikeim
     */
    public newAntikeim() {
        try
        {
            conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/erecruit" , "root" , "123qweasdzxc,");     
        }
        catch(Exception Ex)
        {
            JOptionPane.showMessageDialog(null,Ex);
        }
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        backButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        newAntikeimTable = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        addNewAntikeimenoButton = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        belongsToComboBox = new javax.swing.JComboBox();
        showantikButton = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jobsList = new javax.swing.JList();
        showjobsButton = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 0, 0));
        jButton1.setText("Exit");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1077, 11, -1, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Here you can add a new Antikeim");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(356, 26, -1, -1));

        backButton.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        backButton.setForeground(new java.awt.Color(230, 145, 0));
        backButton.setText("Back to MENU");
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });
        getContentPane().add(backButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 490, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Title");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(51, 149, 31, -1));

        newAntikeimTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null}
            },
            new String [] {
                "title", "description"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(newAntikeimTable);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(51, 184, 532, 46));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Belongs to");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 150, 87, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("Discription of new Antikeim");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(386, 149, 206, -1));

        addNewAntikeimenoButton.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        addNewAntikeimenoButton.setForeground(new java.awt.Color(34, 200, 75));
        addNewAntikeimenoButton.setText("Add New Antikeimeno");
        addNewAntikeimenoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addNewAntikeimenoButtonActionPerformed(evt);
            }
        });
        getContentPane().add(addNewAntikeimenoButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 500, -1, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel7.setText("Complete all the details and then press the button \"Add New Antikeimeno\"");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(126, 61, -1, -1));

        belongsToComboBox.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        getContentPane().add(belongsToComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(867, 192, 240, -1));

        showantikButton.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        showantikButton.setForeground(new java.awt.Color(31, 120, 255));
        showantikButton.setText("Show antikeimena");
        showantikButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showantikButtonActionPerformed(evt);
            }
        });
        getContentPane().add(showantikButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 190, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("Which jobs require this antikeim? Select one or more from the list below");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 290, -1, 30));

        jScrollPane2.setViewportView(jobsList);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 350, 410, -1));

        showjobsButton.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        showjobsButton.setForeground(new java.awt.Color(31, 120, 255));
        showjobsButton.setText("Show Jobs");
        showjobsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showjobsButtonActionPerformed(evt);
            }
        });
        getContentPane().add(showjobsButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 400, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("To select more than one firms press ctr + click");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 320, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        this.dispose();
    }//GEN-LAST:event_backButtonActionPerformed

    private void addNewAntikeimenoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addNewAntikeimenoButtonActionPerformed
        String newtitle = newAntikeimTable.getValueAt(0, 0).toString();
        try // add antikeim
        {   
            String insertQuery;
            String descr = newAntikeimTable.getValueAt(0, 1).toString();
            String belongsto = belongsToComboBox.getSelectedItem().toString();
            
            
            if(belongsto.equals("NULL"))
                 insertQuery = "insert into antikeim (title, descr, belongs_to) values "
                        + "( '" + newtitle +"' , '" +descr + "' , " +belongsto + " )";
            else    
                insertQuery = "insert into antikeim (title, descr, belongs_to) values "
                        + "( '" + newtitle +"' , '" +descr + "' , '" +belongsto + "' )";
            
            JOptionPane.showMessageDialog(null, insertQuery);
            
            pst =conn.prepareStatement(insertQuery);
            pst.execute(); 
        }
        catch (Exception ex)
        {
            JOptionPane.showMessageDialog(null, ex);
        }
        
        try// add into required
        {
            String job="";
            int id =-1;
            java.util.List<String> jobs = jobsList.getSelectedValuesList();
            
            for(int i=0; i<jobs.size(); i++)
            {
                job = jobs.get(i);
                String idQuery = "select id,position from job";
                
                Statement stmt1 = conn.createStatement();
                ResultSet rs1 = stmt1.executeQuery(idQuery);
                while(rs1.next())
                {
                    if(rs1.getString("position").equals(job))
                    {
                        id = rs1.getInt("id");
                    }
                }
                
                String hastomeasQuery="insert into requires (job_id, antikeim_title) values"
                    + "( " +id +" , '" +newtitle +"' )";
            
                JOptionPane.showMessageDialog(null, hastomeasQuery);

                pst =conn.prepareStatement(hastomeasQuery);
                pst.execute();
            }
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_addNewAntikeimenoButtonActionPerformed

    private void showantikButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showantikButtonActionPerformed
        try
        {
            String antikeimQuery="select title from antikeim";

            Statement stmt1 = conn.createStatement();
            ResultSet rs1 = stmt1.executeQuery(antikeimQuery);
            
            while(rs1.next())
            {
                belongsToComboBox.addItem(rs1.getString("title"));
            }
            
            belongsToComboBox.addItem("NULL");
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_showantikButtonActionPerformed

    private void showjobsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showjobsButtonActionPerformed
        try
        {
            int height = jobsList.getComponentCount();
            for(int i=0;i<height;i++)
            {
                jobsList.remove(0);
            }
            DefaultListModel<String> tempjobsList = new DefaultListModel<>();
            
            String firmsQuery="select position from job";            
            Statement stmt1 = conn.createStatement();
            ResultSet rs1 = stmt1.executeQuery(firmsQuery);
            
            while(rs1.next())
            {
                tempjobsList.addElement(rs1.getString("position"));
            }
            
            jobsList.setModel(tempjobsList);
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_showjobsButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addNewAntikeimenoButton;
    private javax.swing.JButton backButton;
    private javax.swing.JComboBox belongsToComboBox;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JList jobsList;
    private javax.swing.JTable newAntikeimTable;
    private javax.swing.JButton showantikButton;
    private javax.swing.JButton showjobsButton;
    // End of variables declaration//GEN-END:variables
}
