package Erecruit_Login;

/**
 *
 * @author Chatzopoulos Thomas
 */
import javax.swing.*;
import java.sql.*;
import java.util.Date;
import java.text.SimpleDateFormat;
import java.time.LocalDateTime;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;

public class newCandidate extends javax.swing.JFrame {
    String username;
    Connection conn=null;
    Statement stmt=null;
    PreparedStatement pst=null;
    ResultSet rs=null;
    String newUsername;
    String newLanguage ="";
    ArrayList<String> languages = new ArrayList<String>();
    
    Date date = new Date();
    SimpleDateFormat formatter = new SimpleDateFormat("dd-MM-yyyy");
    
    public newCandidate() {
        try
        {
            conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/erecruit" , "root" , "123qweasdzxc,");     
        }
        catch(Exception Ex)
        {
            JOptionPane.showMessageDialog(null,Ex);
        }
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        viewYourDatajScrollPane1 = new javax.swing.JScrollPane();
        newCandidateTable = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        candidateEducationTable = new javax.swing.JTable();
        viewLanguagesToggleButton1 = new javax.swing.JToggleButton();
        jScrollPane5 = new javax.swing.JScrollPane();
        languagesTable = new javax.swing.JTable();
        addLanguageButton = new javax.swing.JButton();
        newLanguageComboBox = new javax.swing.JComboBox<String>();
        jScrollPane2 = new javax.swing.JScrollPane();
        projectsTable = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        backButton = new javax.swing.JButton();
        recruiterComboBox = new javax.swing.JComboBox<String>();
        checkRecruiterButton = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        scoreComboBox = new javax.swing.JComboBox<String>();
        durationComboBox = new javax.swing.JComboBox<String>();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        commentsTable = new javax.swing.JTable();
        AddButton = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        checkUsernameButton = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        numberOfProjects = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        newCandidateTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, "", "", null, "now", null, "-"}
            },
            new String [] {
                "username", "password", "name", "surname", "reg_date", "email", "lastLogIn"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                true, true, true, true, false, true, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        viewYourDatajScrollPane1.setViewportView(newCandidateTable);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Here you can add a new Candidate");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setText("Complete all the details and then press the button \"Add New Candidate\"");

        candidateEducationTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null}
            },
            new String [] {
                "Biography", "Sistatikes", "Certificates"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(candidateEducationTable);

        viewLanguagesToggleButton1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        viewLanguagesToggleButton1.setForeground(new java.awt.Color(31, 120, 255));
        viewLanguagesToggleButton1.setText("View Laguages");
        viewLanguagesToggleButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewLanguagesToggleButton1ActionPerformed(evt);
            }
        });

        languagesTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null}
            },
            new String [] {
                "Languages"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane5.setViewportView(languagesTable);

        addLanguageButton.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        addLanguageButton.setForeground(new java.awt.Color(34, 200, 75));
        addLanguageButton.setText("Add Language");
        addLanguageButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addLanguageButtonActionPerformed(evt);
            }
        });

        newLanguageComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "EN", "FR", "SP", "GR" }));
        newLanguageComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newLanguageComboBoxActionPerformed(evt);
            }
        });

        projectsTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null}
            },
            new String [] {
                "Discription", "Url"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane2.setViewportView(projectsTable);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Here you can add candidate's interview data:");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Here you can add candidate's projects:");

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 0, 0));
        jButton1.setText("Exit");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        backButton.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        backButton.setForeground(new java.awt.Color(230, 145, 0));
        backButton.setText("Back to MENU");
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });

        recruiterComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                recruiterComboBoxActionPerformed(evt);
            }
        });

        checkRecruiterButton.setFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        checkRecruiterButton.setForeground(new java.awt.Color(230, 145, 0));
        checkRecruiterButton.setText("check recruiter");
        checkRecruiterButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkRecruiterButtonActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Score");

        scoreComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "0", "1", "2", "3", "4" }));

        durationComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "00:00:00", "00:01:00", "00:02:00", "00:03:00", "00:04:00", "00:05:00", "00:06:00", "00:07:00", "00:08:00", "00:09:00", "00:10:00", "00:11:00", "00:12:00", "00:13:00", "00:14:00", "00:15:00", "00:16:00", "00:17:00", "00:18:00", "00:19:00", "00:20:00", "00:21:00", "00:22:00", "00:23:00", "00:24:00", "00:25:00", "00:26:00", "00:27:00", "00:28:00", "00:29:00", "00:30:00", "00:31:00", "00:32:00", "00:33:00", "00:34:00", "00:35:00", "00:36:00", "00:37:00", "00:38:00", "00:39:00", "00:40:00", "00:41:00", "00:42:00", "00:43:00", "00:44:00", "00:45:00", "00:46:00", "00:47:00", "00:48:00", "00:49:00", "00:50:00", "00:51:00", "00:52:00", "00:53:00", "00:54:00", "00:55:00", "00:56:00", "00:57:00", "00:58:00", "00:59:00" }));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("Duration");

        commentsTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null}
            },
            new String [] {
                "comments", "start_date"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane3.setViewportView(commentsTable);

        AddButton.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        AddButton.setForeground(new java.awt.Color(34, 200, 75));
        AddButton.setText("Add New Candidate");
        AddButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddButtonActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("You can add 4 Laguages (one per time)");

        checkUsernameButton.setFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        checkUsernameButton.setForeground(new java.awt.Color(230, 145, 0));
        checkUsernameButton.setText("check username");
        checkUsernameButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkUsernameButtonActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setText("How many projects does the new candidate have?");

        numberOfProjects.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numberOfProjectsActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel9.setText("Note: the date shoud be of this form: YYYY-MM-DD");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(129, 129, 129)
                        .addComponent(jLabel2)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(366, 366, 366)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(newLanguageComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33)
                        .addComponent(addLanguageButton, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33)
                        .addComponent(viewLanguagesToggleButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(checkUsernameButton)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel4)
                            .addGap(100, 100, 100)
                            .addComponent(jLabel8)
                            .addGap(28, 28, 28)
                            .addComponent(numberOfProjects, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 986, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(viewYourDatajScrollPane1)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 986, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel3)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(checkRecruiterButton)
                                        .addComponent(recruiterComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGap(44, 44, 44)
                                            .addComponent(jLabel5)
                                            .addGap(37, 37, 37))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(scoreComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(27, 27, 27)))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(durationComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGap(42, 42, 42)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 539, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel9)))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(255, 255, 255)
                            .addComponent(backButton)
                            .addGap(102, 102, 102)
                            .addComponent(AddButton))))
                .addContainerGap(80, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(viewYourDatajScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(checkUsernameButton)
                .addGap(3, 3, 3)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(newLanguageComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(addLanguageButton)
                        .addComponent(jLabel7)))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(viewLanguagesToggleButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel8)
                    .addComponent(numberOfProjects, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(checkRecruiterButton)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(recruiterComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(durationComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(scoreComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(backButton)
                    .addComponent(AddButton))
                .addGap(39, 39, 39))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void viewLanguagesToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewLanguagesToggleButton1ActionPerformed
        try
        {
            int height = languagesTable.getRowCount();
            for(int i=0;i<height;i++)
            {
                ((DefaultTableModel)languagesTable.getModel()).removeRow(0);
            }  
            DefaultTableModel temporaryTable = (DefaultTableModel) languagesTable.getModel();
            
            
            
            boolean exists = false;
            for(int i=0; i<languages.size(); i++)
            {
                if(newLanguage.equals(languages.get(i)))
                {
                    exists = true;
                }
            }
            
            if(!exists) //αν δεν υπάρχει ήδη
                languages.add(newLanguage);
            
            String langfortable="";
            for(int i=0; i<languages.size(); i++)
            {
                if(languages.isEmpty())
                    continue;
                
                if(i==languages.size()-1)//τελευταία επανάληψη
                    langfortable += languages.get(i);
                else
                    langfortable += languages.get(i) + ",";
            }
            
            for(int i=0; i<height; i++)
            {
                temporaryTable.addRow(new Object[] { langfortable });
            }
            languagesTable.setModel(temporaryTable);
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null,e);
        }
    }//GEN-LAST:event_viewLanguagesToggleButton1ActionPerformed

    private void addLanguageButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addLanguageButtonActionPerformed
        try
        {
            newLanguage = newLanguageComboBox.getSelectedItem().toString();
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null,e);
        }
    }//GEN-LAST:event_addLanguageButtonActionPerformed

    private void newLanguageComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newLanguageComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_newLanguageComboBoxActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        this.dispose();
    }//GEN-LAST:event_backButtonActionPerformed

    private void recruiterComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_recruiterComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_recruiterComboBoxActionPerformed

    private void checkRecruiterButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkRecruiterButtonActionPerformed
        // TODO add your handling code here:
        try 
        {
            recruiterComboBox.removeAllItems(); 
            String recruiterQuery="select username from recruiter";
                      
            Statement stmt = conn.createStatement();
            ResultSet rs = stmt.executeQuery(recruiterQuery);
            while(rs.next())
            {
                String titlos=rs.getString("username");
                recruiterComboBox.addItem(titlos);               
            }                   
        }                         
        catch (Exception ex)
        {
            JOptionPane.showMessageDialog(null, ex);
        }
    }//GEN-LAST:event_checkRecruiterButtonActionPerformed
//add new candidate
    private void AddButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddButtonActionPerformed
        try //add user
        {
            String insertQ;
            newUsername=newCandidateTable.getValueAt(0,0).toString();
            String UserInsertQuery = "insert into user (username, password, name, surname, reg_date, email, lastLogIn) values (";
            
            for(int i=0;i<newCandidateTable.getColumnCount();i++)
            {
                insertQ = newCandidateTable.getValueAt(0, i).toString();
                if(i==0)
                    UserInsertQuery += "'" +insertQ +"'";
                else if(i==4) //reg_date = now
                    UserInsertQuery += " , '" +LocalDateTime.now() +"'";
                else if(i==6)
                    UserInsertQuery += " , " +"NULL";
                else
                    UserInsertQuery += " , '" +insertQ +"'";
            }  
            UserInsertQuery += ");";
            
            JOptionPane.showMessageDialog(null, UserInsertQuery);

            pst =conn.prepareStatement(UserInsertQuery);
            pst.execute();
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, e);
        }
        
        
        try //add biograpgy
        {
            String insertQ;
            String UserEduInsertQuery = "insert into candidate (username, bio, sistatikes, certificates) values ('"+ newUsername +"' , ";
            
            for(int i=0;i<candidateEducationTable.getColumnCount();i++)
            {
                insertQ = candidateEducationTable.getValueAt(0, i).toString();
                if(i==0)
                    UserEduInsertQuery += "'" +insertQ +"'";
                else
                    UserEduInsertQuery += " , '" +insertQ +"'";
            }  
            UserEduInsertQuery += ");";
            
            JOptionPane.showMessageDialog(null, UserEduInsertQuery);

            pst =conn.prepareStatement(UserEduInsertQuery);
            pst.execute();
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, e);
        }
        
        
        try //add projects
        {
            String insertQ;
                       
            String UserProjInsertQuery = "insert into project (candid, num, descr, url) values \n";
            
            for(int j=0; j<projectsTable.getRowCount(); j++) //για καθε προτζεκτ
            {
                UserProjInsertQuery += "('"+ newUsername +"' , " +(j+1);
                
                for(int i=0;i<projectsTable.getColumnCount();i++)
                {
                    insertQ = projectsTable.getValueAt(j, i).toString();
                    UserProjInsertQuery += " , '" +insertQ +"'";
                }
                if(j != projectsTable.getRowCount()-1)
                    UserProjInsertQuery += "), \n";
                else
                    UserProjInsertQuery += ")";
            }
                
            
            JOptionPane.showMessageDialog(null,UserProjInsertQuery );

            pst =conn.prepareStatement(UserProjInsertQuery);
            pst.execute();
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, e);
        }
        
        
        
        try // add interview
        {    
            String recruiterFromComboBox = recruiterComboBox.getSelectedItem().toString();
            String scoreFromComboBox = scoreComboBox.getSelectedItem().toString();
            String durationFromComboBox = durationComboBox.getSelectedItem().toString();
            String startdateFromTable = (String) commentsTable.getValueAt(0, 1).toString();
            String commentsFromTable = (String) commentsTable.getValueAt(0,0).toString();
           
            
            String insertQuery="insert into interview (candidate_username, recruiter_username, score, duration, start_date, comments) values ("
                                + "'"+ newUsername +"' , '"+ recruiterFromComboBox +"' , "+ (scoreFromComboBox +1) +" , \""+durationFromComboBox +"\" , '"+ startdateFromTable+"' , '"+ commentsFromTable +"');";            

            
            JOptionPane.showMessageDialog(null, insertQuery);
            
            pst =conn.prepareStatement(insertQuery);
            pst.execute(); 
        }
        catch (NumberFormatException | SQLException ex)
        {
            JOptionPane.showMessageDialog(null, ex);
        }
        
        try// languages
        {
            String languageQuery="select * from languages where candid LIKE '" +newUsername +"'";
            String languageq="";
            
            Statement stmt1 = conn.createStatement();
            ResultSet rs1 = stmt1.executeQuery(languageQuery);
                       
            String lang = languagesTable.getValueAt(0, 0).toString();
            
            if(!rs1.next()) //ο χρηστης δεν εχει καμια γλωσσα ακομα
            {
                languageq="Insert into languages(candid, lang) values ('"+ newUsername +"','"+ lang +"')";
            }
            else
            {
                languageq="Update languages set lang='"+ lang +"'where candid LIKE '%" +newUsername +"%' ";
            }
            
            pst =conn.prepareStatement(languageq);
            pst.execute();
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, e);
        }
        
    }//GEN-LAST:event_AddButtonActionPerformed

    private void checkUsernameButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkUsernameButtonActionPerformed
        // TODO add your handling code here:
        try
        {
           String usercheck ="select username from user";
           
           Statement stmt1 = conn.createStatement();
           ResultSet rs1 = stmt1.executeQuery(usercheck);
           
           boolean exists=false;
           while(rs1.next())
           {
               if(rs1.getString("username").equals(newCandidateTable.getValueAt(0, 0).toString()))
               {
                   JOptionPane.showMessageDialog(null, "Username exists in database!\nPlease try a new one");
                   newCandidateTable.setValueAt("", 0, 0);
                   exists = true;
               }
           }
           if(!exists)
               JOptionPane.showMessageDialog(null, "Username is ok");
           
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_checkUsernameButtonActionPerformed

    private void numberOfProjectsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numberOfProjectsActionPerformed
        // TODO add your handling code here:
        int numofprojects = Integer.parseInt(numberOfProjects.getText());
        
        int height = projectsTable.getRowCount();
        for(int i=0;i<height;i++)
        {
            ((DefaultTableModel)projectsTable.getModel()).removeRow(0);
        }
            
        DefaultTableModel tempProjectsTable =  (DefaultTableModel)projectsTable.getModel();   
        
        
        for(int i=0; i<numofprojects; i++)
            tempProjectsTable.addRow(new Object[]{});
        
                
    }//GEN-LAST:event_numberOfProjectsActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddButton;
    private javax.swing.JButton addLanguageButton;
    private javax.swing.JButton backButton;
    private javax.swing.JTable candidateEducationTable;
    private javax.swing.JButton checkRecruiterButton;
    private javax.swing.JButton checkUsernameButton;
    private javax.swing.JTable commentsTable;
    private javax.swing.JComboBox<String> durationComboBox;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTable languagesTable;
    private javax.swing.JTable newCandidateTable;
    private javax.swing.JComboBox<String> newLanguageComboBox;
    private javax.swing.JTextField numberOfProjects;
    private javax.swing.JTable projectsTable;
    private javax.swing.JComboBox<String> recruiterComboBox;
    private javax.swing.JComboBox<String> scoreComboBox;
    private javax.swing.JToggleButton viewLanguagesToggleButton1;
    private javax.swing.JScrollPane viewYourDatajScrollPane1;
    // End of variables declaration//GEN-END:variables
}
