package Erecruit_Login;

import javax.swing.*;
import java.sql.*;
import java.time.LocalDateTime;

/**
 *
 * @author panag
 */
public class newRecruiter extends javax.swing.JFrame {
      
    String newUsername ="";
    Connection conn=null;
    Statement stmt=null;
    PreparedStatement pst=null;
    ResultSet rs=null;

    public newRecruiter() 
    {
        try
        {
            conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/erecruit" , "root" , "123qweasdzxc,");     
        }
        catch(Exception Ex)
        {
            JOptionPane.showMessageDialog(null,Ex);
        }        
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        newUserTable = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        exitButton = new javax.swing.JButton();
        backToMenuButton = new javax.swing.JButton();
        addnewRecruiterButton = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        expyearsTextField = new javax.swing.JTextField();
        etaireiesComboBox = new javax.swing.JComboBox();
        showfirmsbutton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        newUserTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, "now", null, "-"}
            },
            new String [] {
                "username", "password", "name", "surname", "reg_date", "email", "lastLogIn"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                true, true, true, true, false, true, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(newUserTable);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 158, 913, 45));

        jButton1.setFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(230, 145, 0));
        jButton1.setText("Check Username");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 221, 151, 40));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Here you can add a new Recruiter");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(347, 43, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setText("Complete all the details and then press the button \"Add New Recruiter\"");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 83, -1, -1));

        exitButton.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        exitButton.setForeground(new java.awt.Color(255, 0, 0));
        exitButton.setText("Exit");
        exitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitButtonActionPerformed(evt);
            }
        });
        getContentPane().add(exitButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(1070, 10, -1, -1));

        backToMenuButton.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        backToMenuButton.setForeground(new java.awt.Color(230, 145, 0));
        backToMenuButton.setText("Back to Menu");
        backToMenuButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backToMenuButtonActionPerformed(evt);
            }
        });
        getContentPane().add(backToMenuButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(248, 375, -1, -1));

        addnewRecruiterButton.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        addnewRecruiterButton.setForeground(new java.awt.Color(34, 200, 75));
        addnewRecruiterButton.setText("Add New Recruiter");
        addnewRecruiterButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addnewRecruiterButtonActionPerformed(evt);
            }
        });
        getContentPane().add(addnewRecruiterButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(604, 375, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("How many years of experience does this recruiter have?");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 294, 360, 26));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Which firm does this recruiter belong to?");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 331, 341, 24));
        getContentPane().add(expyearsTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(528, 300, 30, -1));

        etaireiesComboBox.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        getContentPane().add(etaireiesComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 330, 166, -1));

        showfirmsbutton.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        showfirmsbutton.setForeground(new java.awt.Color(31, 120, 255));
        showfirmsbutton.setText("Show Firms");
        showfirmsbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showfirmsbuttonActionPerformed(evt);
            }
        });
        getContentPane().add(showfirmsbutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 330, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try
        {
           String usercheck ="select username from user";
           
           Statement stmt1 = conn.createStatement();
           ResultSet rs1 = stmt1.executeQuery(usercheck);
           
           boolean exists=false;
           while(rs1.next())
           {
               if(rs1.getString("username").equals(newUserTable.getValueAt(0, 0).toString()))
               {
                   JOptionPane.showMessageDialog(null, "Username exists in database!\nPlease try a new one");
                   newUserTable.setValueAt("", 0, 0);
                   exists = true;
               }
           }
           if(!exists)
               JOptionPane.showMessageDialog(null, "Username is ok");
           
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void exitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitButtonActionPerformed
        System.exit(0);
    }//GEN-LAST:event_exitButtonActionPerformed

    private void backToMenuButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backToMenuButtonActionPerformed
        this.dispose();
    }//GEN-LAST:event_backToMenuButtonActionPerformed

    private void addnewRecruiterButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addnewRecruiterButtonActionPerformed
        try //add user
        {
            String insertQ;
            newUsername=newUserTable.getValueAt(0,0).toString();
            String UserInsertQuery = "insert into user (username, password, name, surname, reg_date, email, lastLogIn) values (";
            
            for(int i=0;i<newUserTable.getColumnCount();i++)
            {
                insertQ = newUserTable.getValueAt(0, i).toString();
                if(i==0)
                    UserInsertQuery += "'" +insertQ +"'";
                else if(i==4) //reg_date = now
                    UserInsertQuery += " , '" +LocalDateTime.now() +"'";
                else if(i==6) //δεν εχει κανει ποτέ log in καθώς είναι καινούριος user
                    UserInsertQuery += " , " +"NULL";
                else
                    UserInsertQuery += " , '" +insertQ +"'";
            }  
            UserInsertQuery += ");";
            
            JOptionPane.showMessageDialog(null, UserInsertQuery);

            pst =conn.prepareStatement(UserInsertQuery);
            pst.execute();
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, e);
        }
        
        
        try //add recruiter
        {
            int expyears = Integer.parseInt(expyearsTextField.getText());
            String firm = etaireiesComboBox.getSelectedItem().toString();
            String afm="";
            
            String afmQuery = "select afm,name from etaireia";
            Statement stmt1 = conn.createStatement();
            ResultSet rs1 = stmt1.executeQuery(afmQuery);
            
            while(rs1.next())
            {
                if(rs1.getString("name").equals(firm))
                {
                    afm = rs1.getString("afm");
                }
            }
            
            String recinsert = " insert into recruiter (username , exp_years , firm) values "
                    + "('" +newUsername + "' , " + expyears + " , '" +afm +"' )";
            
            
            JOptionPane.showMessageDialog(null, recinsert);
            pst =conn.prepareStatement(recinsert);
            pst.execute();
            
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_addnewRecruiterButtonActionPerformed

    private void showfirmsbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showfirmsbuttonActionPerformed
        try
        {
            String firmsQuery="select name from etaireia";

            Statement stmt1 = conn.createStatement();
            ResultSet rs1 = stmt1.executeQuery(firmsQuery);
            
            while(rs1.next())
            {
                etaireiesComboBox.addItem(rs1.getString("name"));
            }
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_showfirmsbuttonActionPerformed

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addnewRecruiterButton;
    private javax.swing.JButton backToMenuButton;
    private javax.swing.JComboBox etaireiesComboBox;
    private javax.swing.JButton exitButton;
    private javax.swing.JTextField expyearsTextField;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable newUserTable;
    private javax.swing.JButton showfirmsbutton;
    // End of variables declaration//GEN-END:variables
}
