package Erecruit_Login;

import javax.swing.*;
import java.sql.*;
import java.util.List;
/**
 *
 * @author panag
 */
public class newTomeas extends javax.swing.JFrame {
    
    String username;
    Connection conn=null;
    Statement stmt=null;
    PreparedStatement pst=null;
    ResultSet rs=null;
    
    public newTomeas() {
        try
        {
            conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/erecruit" , "root" , "123qweasdzxc,");     
        }
        catch(Exception Ex)
        {
            JOptionPane.showMessageDialog(null,Ex);
        }
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        newTomeasTable = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        categoriesComboBox = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        backToMenuButton = new javax.swing.JButton();
        addnewTomeasButton = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        showCategoriesButton = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        firmsList = new javax.swing.JList();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        newTomeasTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null}
            },
            new String [] {
                "title", "keimeno"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(newTomeasTable);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(174, 132, 733, 47));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Is this Tomeas a new one or does it belong to one of the already existing categories below?");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 190, 760, 30));

        categoriesComboBox.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        getContentPane().add(categoriesComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 270, 268, 38));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("If it is a new one please select null on the box below. If it belongs to a category from those below please select it");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 230, -1, 31));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("To select more than one firms press ctr + click");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 360, -1, 27));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel4.setText("Complete all the details and then press the button \"Add New Tomeas\"");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(139, 71, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel5.setText("Here you can add a new Tomeas");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(373, 20, -1, -1));

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 0, 0));
        jButton1.setText("Exit");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1025, 22, -1, -1));

        backToMenuButton.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        backToMenuButton.setForeground(new java.awt.Color(230, 145, 0));
        backToMenuButton.setText("Back to Menu");
        backToMenuButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backToMenuButtonActionPerformed(evt);
            }
        });
        getContentPane().add(backToMenuButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 520, -1, -1));

        addnewTomeasButton.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        addnewTomeasButton.setForeground(new java.awt.Color(34, 200, 75));
        addnewTomeasButton.setText("Add new Tomeas");
        addnewTomeasButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addnewTomeasButtonActionPerformed(evt);
            }
        });
        getContentPane().add(addnewTomeasButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 530, -1, -1));

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton2.setForeground(new java.awt.Color(31, 120, 255));
        jButton2.setText("Show firms");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 440, -1, -1));

        showCategoriesButton.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        showCategoriesButton.setForeground(new java.awt.Color(31, 120, 255));
        showCategoriesButton.setText("Show Categories");
        showCategoriesButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showCategoriesButtonActionPerformed(evt);
            }
        });
        getContentPane().add(showCategoriesButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(174, 273, -1, -1));

        firmsList.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        firmsList.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(firmsList);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 420, 300, 70));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("Which Firms have this tomeas? Select one or more from the list below");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(328, 326, -1, 27));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backToMenuButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backToMenuButtonActionPerformed
        this.dispose();
    }//GEN-LAST:event_backToMenuButtonActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        try
        {
            int height = firmsList.getComponentCount();
            for(int i=0;i<height;i++)
            {
                firmsList.remove(0);
            }
            DefaultListModel<String> tempfirmsList = new DefaultListModel<>();
            
            String firmsQuery="select name from etaireia";            
            Statement stmt1 = conn.createStatement();
            ResultSet rs1 = stmt1.executeQuery(firmsQuery);
            
            while(rs1.next())
            {
                tempfirmsList.addElement(rs1.getString("name"));
            }
            
            firmsList.setModel(tempfirmsList);
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void showCategoriesButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showCategoriesButtonActionPerformed
        try
        {
            String firmsQuery="select title from tomeas";

            Statement stmt1 = conn.createStatement();
            ResultSet rs1 = stmt1.executeQuery(firmsQuery);
            
            while(rs1.next())
            {
                categoriesComboBox.addItem(rs1.getString("title"));
            }
            
            categoriesComboBox.addItem("NULL");
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, e);
        }
        
    }//GEN-LAST:event_showCategoriesButtonActionPerformed

    private void addnewTomeasButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addnewTomeasButtonActionPerformed
        String newtitle = newTomeasTable.getValueAt(0, 0).toString();
        try //insert into tomeas
        {
            
            String newkeimeno = newTomeasTable.getValueAt(0, 1).toString();
            String newtomeastitle = categoriesComboBox.getSelectedItem().toString();

            String tomeasQuery="insert into tomeas (title, keimeno, tomeas_title) values"
                    + "( '" +newtitle +"' , '" +newkeimeno +"' , '" +newtomeastitle +"' )";
            
            JOptionPane.showMessageDialog(null, tomeasQuery);

            pst =conn.prepareStatement(tomeasQuery);
            pst.execute();
            
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, e);
        }
        
        try // insert into has_tomea
        {
            String afm="",etaireia="";
            List<String> firms = firmsList.getSelectedValuesList();
            
            for(int i=0; i<firms.size(); i++)
            {
                etaireia = firms.get(i);
                String afmQuery = "select afm,name from etaireia";
                
                Statement stmt1 = conn.createStatement();
                ResultSet rs1 = stmt1.executeQuery(afmQuery);
                while(rs1.next())
                {
                    if(rs1.getString("name").equals(etaireia))
                    {
                        afm = rs1.getString("afm");
                    }
                }
                
                String hastomeasQuery="insert into has_tomea (tomeas_title, etaireia_AFM) values"
                    + "( '" +newtitle +"' , '" +afm +"' )";
            
                JOptionPane.showMessageDialog(null, hastomeasQuery);

                pst =conn.prepareStatement(hastomeasQuery);
                pst.execute();
            }
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, e);
        }
        
    }//GEN-LAST:event_addnewTomeasButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addnewTomeasButton;
    private javax.swing.JButton backToMenuButton;
    private javax.swing.JComboBox categoriesComboBox;
    private javax.swing.JList firmsList;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable newTomeasTable;
    private javax.swing.JButton showCategoriesButton;
    // End of variables declaration//GEN-END:variables
}
